export const en = {
    "": "",
    "project-tasks": "Project Tasks",
    "submit-support-ticket": "Submit Support ticket",
    "store-view": "Store View",
    "select-store": "Select Store",
    "app-settings-animation-sp": "App Settings Animation Speed seconds",
    "app-settings": "App Settings",
    "animation-speed-seconds": "Animation Speed seconds",
    "seconds": "seconds",
    "animation-speed": "Animation Speed",
    "users": "Users",
    "user-history": "User History",
    "contracts": "Contracts",
    "profile": "Profile",
    "search-results": "Search Results",
    "loading-from-database": "Loading from Database",
    "this-website-uses-cookies": "This website uses cookies We use cookies to personalise content and ads to provide social media features and to analyse our traffic We also share information about your use of our site with our social media advertising and analytics partners who may combine it with other information that youve provided to them or that theyve collected from your use of their services Agree Decline",
    "agree": "Agree",
    "decline": "Decline",
    "unauthorized-login-to-gai": "Unauthorized Login to gain access",
    "unauthorized": "Unauthorized",
    "login-to-gain-access": "Login to gain access",
    "login": "Login"
};
