export const en = {
    "unauthorized-login-to-gain-access": "Unauthorized Login to gain access",
    "transunauthorized-trans": "TransUnauthorized Trans",
    "trans-login-to-gain-access-trans": "Trans Login to gain access Trans",
    "translogintrans": "TransLoginTrans",
    "welcome": "Welcome",
    "client-login": "Client Login",
    "ver-0206": "Ver 0206",
    "k1-user-responsibilities": "1 User Responsibilities",
    "by-using-this-website-you-agree-to": "By using this website you agree to",
    "comply-with-all-applicable-laws-and-regulations": "Comply with all applicable laws and regulations",
    "k2-intellectual-property": "2 Intellectual Property",
    "k3-disclaimers": "3 Disclaimers",
    "k4-limitation-of-liability": "4 Limitation of Liability",
    "k5-privacy-policy": "5 Privacy Policy",
    "k6-changes-to-terms": "6 Changes to Terms",
    "k7-contact-us": "7 Contact Us",
    "privacy-policy": "Privacy Policy",
    "information-we-collect": "Information We Collect",
    "personal-information": "Personal Information",
    "log-data": "Log Data",
    "cookies": "Cookies",
    "how-we-use-your-information": "How We Use Your Information",
    "we-may-use-the-information-we-collect-for-various-purposes-including": "We may use the information we collect for various purposes including",
    "providing-and-improving-our-services": "Providing and improving our services",
    "communicating-with-you": "Communicating with you",
    "analyzing-website-usage-and-trends": "Analyzing website usage and trends",
    "preventing-fraud-and-enhancing-security": "Preventing fraud and enhancing security",
    "sharing-your-information": "Sharing Your Information",
    "service-providers-who-assist-us-in-delivering-our-services": "Service providers who assist us in delivering our services",
    "law-enforcement-or-government-authorities-when-required-by-law": "Law enforcement or government authorities when required by law",
    "security": "Security",
    "your-choices": "Your Choices",
    "changes-to-this-privacy-policy": "Changes to this Privacy Policy",
    "contact-us": "Contact Us",
    "work-smarter-with-custom-tools": "Work smarter with custom tools",
    "centralize-workflow-with-online-customers-reach-new-markets": "Centralize workflow with online customers reach new markets",
    "achieve-the-benefits-of-a-web-presence-and-a-mobile-app-with-a-single-entity": "Achieve the benefits of a web presence and a mobile app with a single entity",
    "cement-brand-and-stand-out": "Cement brand and stand out",
    "project-tasks": "Project Tasks",
    "submit-support-ticket": "Submit Support ticket",
    "store-view": "Store View",
    "select-store": "Select Store",
    "app-settings": "App Settings",
    "seconds": "seconds",
    "darkmode": "Darkmode",
    "animation-speed": "Animation Speed",
    "loading-profile": "Loading profile",
    "stores": "Stores",
    "contracts": "Contracts",
    "users": "Users",
    "no-users-found": "No users found",
    "user-history": "User History",
    "job": "Job",
    "task": "Task",
    "date": "Date",
    "stage": "Stage",
    "contractor": "Contractor",
    "picker": "Picker",
    "k000-usd": "000 USD",
    "date-item-cost-compdate": "Date Item Cost CompDate",
    "item": "Item",
    "cost": "Cost",
    "compdate": "CompDate",
    "reload": "Reload",
    "profile": "Profile",
    "update-entry": "Update Entry",
    "search-results": "Search Results",
    "agree": "Agree",
    "decline": "Decline"
};
